// Code generated by apps/cli-go/codegen/gen-client.mjs; DO NOT EDIT.
//
// Quelle: apps/cli/mcp/devd-mcp.js (via Introspektions-Harness DD2-199).
// Ein Client-Func je Single-apiRequest-MCP-Tool (DD2-203 Handler-Parser, DD2-205 D06-Namen).
// Nicht-generierbare Tools (multi-call / async Pfad-Resolution / Bulk-Business-Logic)
// bleiben Handarbeit im Manual-Layer (DD2#36).
// Regenerieren: node apps/cli-go/codegen/gen-client.mjs

package api

import (
	"encoding/json"
	"fmt"
	"net/url"

	"devd-cli/internal/api/generated"
)

// BacklogExport entspricht MCP-Tool devd_backlog_export.
func (c *Client) BacklogExport(args generated.BacklogExportArgs) (json.RawMessage, error) {
	q := url.Values{}
	if args.Format != nil {
		q.Set("format", string(*args.Format))
	}
	if args.Status != nil {
		q.Set("status", *args.Status)
	}
	if args.Search != nil {
		q.Set("search", *args.Search)
	}
	path := "/api/backlog-export"
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// DashboardHome entspricht MCP-Tool devd_dashboard_home.
func (c *Client) DashboardHome(args generated.DashboardHomeArgs) (json.RawMessage, error) {
	path := "/api/dashboard/home"
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// DependenciesGraph entspricht MCP-Tool devd_dependencies_graph.
func (c *Client) DependenciesGraph(args generated.DependenciesGraphArgs) (json.RawMessage, error) {
	var err error
	var sprintKeySprintID int
	if args.SprintKey != nil {
		sprintKeySprintID, err = c.ResolveSprintID(*args.SprintKey)
		if err != nil {
			return nil, err
		}
	}
	q := url.Values{}
	if args.SprintKey != nil {
		q.Set("sprint_id", fmt.Sprintf("%d", sprintKeySprintID))
	}
	path := "/api/dependencies/graph"
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// IssueActivity entspricht MCP-Tool devd_issue_activity.
func (c *Client) IssueActivity(args generated.IssueActivityArgs) (json.RawMessage, error) {
	var err error
	idOrKeyIssueID, err := c.ResolveIssueID(args.IdOrKey)
	if err != nil {
		return nil, err
	}
	q := url.Values{}
	if args.Limit != nil {
		q.Set("limit", fmt.Sprintf("%v", *args.Limit))
	}
	path := "/api/backlog/" + fmt.Sprintf("%d", idOrKeyIssueID) + "/activity"
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// IssueAssignSprint entspricht MCP-Tool devd_issue_assign_sprint.
func (c *Client) IssueAssignSprint(args generated.IssueAssignSprintArgs) (json.RawMessage, error) {
	var err error
	idOrKeyIssueID, err := c.ResolveIssueID(args.IdOrKey)
	if err != nil {
		return nil, err
	}
	body := map[string]any{}
	body["sprint_id"] = "null"
	path := "/api/backlog/" + fmt.Sprintf("%d", idOrKeyIssueID) + "/sprint"
	data, err := c.Do("PATCH", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// IssueCreate entspricht MCP-Tool devd_issue_create.
func (c *Client) IssueCreate(args generated.IssueCreateArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["title"] = args.Title
	body["type"] = args.Type
	if args.Priority != nil {
		body["priority"] = *args.Priority
	}
	if args.Goal != nil {
		body["goal"] = *args.Goal
	}
	if args.PoNotes != nil {
		body["po_notes"] = *args.PoNotes
	}
	path := "/api/backlog"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// IssueDelete entspricht MCP-Tool devd_issue_delete.
func (c *Client) IssueDelete(args generated.IssueDeleteArgs) (json.RawMessage, error) {
	var err error
	idOrKeyIssueID, err := c.ResolveIssueID(args.IdOrKey)
	if err != nil {
		return nil, err
	}
	q := url.Values{}
	if args.Force != nil && *args.Force {
		q.Set("force", "1")
	}
	path := "/api/backlog/" + fmt.Sprintf("%d", idOrKeyIssueID)
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("DELETE", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// IssueDepAdd entspricht MCP-Tool devd_issue_dep_add.
func (c *Client) IssueDepAdd(args generated.IssueDepAddArgs) (json.RawMessage, error) {
	var err error
	idOrKeyIssueID, err := c.ResolveIssueID(fmt.Sprintf("%v", args.IdOrKey))
	if err != nil {
		return nil, err
	}
	dependsOnIssueID, err := c.ResolveIssueID(fmt.Sprintf("%v", args.DependsOn))
	if err != nil {
		return nil, err
	}
	body := map[string]any{}
	body["depends_on_id"] = dependsOnIssueID
	if args.Note != nil {
		body["note"] = *args.Note
	}
	path := "/api/backlog/" + fmt.Sprintf("%d", idOrKeyIssueID) + "/dependencies"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// IssueDepList entspricht MCP-Tool devd_issue_dep_list.
func (c *Client) IssueDepList(args generated.IssueDepListArgs) (json.RawMessage, error) {
	var err error
	idOrKeyIssueID, err := c.ResolveIssueID(args.IdOrKey)
	if err != nil {
		return nil, err
	}
	path := "/api/backlog/" + fmt.Sprintf("%d", idOrKeyIssueID) + "/dependencies"
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// IssueLost entspricht MCP-Tool devd_issue_lost.
func (c *Client) IssueLost(args generated.IssueLostArgs) (json.RawMessage, error) {
	path := "/api/backlog/lost"
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// IssueShow entspricht MCP-Tool devd_issue_show.
func (c *Client) IssueShow(args generated.IssueShowArgs) (json.RawMessage, error) {
	var err error
	idOrKeyIssueID, err := c.ResolveIssueID(args.IdOrKey)
	if err != nil {
		return nil, err
	}
	path := "/api/backlog/" + fmt.Sprintf("%d", idOrKeyIssueID)
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// IssueStatus entspricht MCP-Tool devd_issue_status.
func (c *Client) IssueStatus(args generated.IssueStatusArgs) (json.RawMessage, error) {
	var err error
	idOrKeyIssueID, err := c.ResolveIssueID(args.IdOrKey)
	if err != nil {
		return nil, err
	}
	body := map[string]any{}
	body["status"] = args.Status
	if args.Notes != nil {
		body["notes"] = *args.Notes
	}
	path := "/api/backlog/" + fmt.Sprintf("%d", idOrKeyIssueID) + "/status"
	data, err := c.Do("PATCH", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// IssueUpdate entspricht MCP-Tool devd_issue_update.
func (c *Client) IssueUpdate(args generated.IssueUpdateArgs) (json.RawMessage, error) {
	var err error
	idOrKeyIssueID, err := c.ResolveIssueID(args.IdOrKey)
	if err != nil {
		return nil, err
	}
	body := map[string]any{}
	if args.Title != nil {
		body["title"] = *args.Title
	}
	if args.Goal != nil {
		body["goal"] = *args.Goal
	}
	if args.Background != nil {
		body["background"] = *args.Background
	}
	if args.ContextNotes != nil {
		body["context_notes"] = *args.ContextNotes
	}
	if args.RelevantFiles != nil {
		body["relevant_files"] = *args.RelevantFiles
	}
	if args.Priority != nil {
		body["priority"] = *args.Priority
	}
	if args.Type != nil {
		body["type"] = *args.Type
	}
	if args.PoNotes != nil {
		body["po_notes"] = *args.PoNotes
	}
	path := "/api/backlog/" + fmt.Sprintf("%d", idOrKeyIssueID)
	data, err := c.Do("PUT", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MemoryTagCreate entspricht MCP-Tool devd_memory_tag_create.
func (c *Client) MemoryTagCreate(args generated.MemoryTagCreateArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["tag"] = args.Tag
	if args.Description != nil {
		body["description"] = *args.Description
	}
	path := "/api/project-memory-tags"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MemoryTagDelete entspricht MCP-Tool devd_memory_tag_delete.
func (c *Client) MemoryTagDelete(args generated.MemoryTagDeleteArgs) (json.RawMessage, error) {
	path := "/api/project-memory-tags/" + url.PathEscape(args.Tag)
	data, err := c.Do("DELETE", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MemoryTagList entspricht MCP-Tool devd_memory_tag_list.
func (c *Client) MemoryTagList(args generated.MemoryTagListArgs) (json.RawMessage, error) {
	q := url.Values{}
	if args.Query != nil {
		q.Set("query", *args.Query)
	}
	path := "/api/project-memory-tags"
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MemoryTagPrune entspricht MCP-Tool devd_memory_tag_prune.
func (c *Client) MemoryTagPrune(args generated.MemoryTagPruneArgs) (json.RawMessage, error) {
	body := map[string]any{}
	path := "/api/project-memory-tags/prune"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MemoryTagRename entspricht MCP-Tool devd_memory_tag_rename.
func (c *Client) MemoryTagRename(args generated.MemoryTagRenameArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["old"] = args.Old
	body["new"] = args.New
	path := "/api/project-memory-tags/rename"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneActivity entspricht MCP-Tool devd_milestone_activity.
func (c *Client) MilestoneActivity(args generated.MilestoneActivityArgs) (json.RawMessage, error) {
	q := url.Values{}
	if args.Limit != nil {
		q.Set("limit", fmt.Sprintf("%v", *args.Limit))
	}
	path := "/api/milestones/" + fmt.Sprintf("%v", args.MilestoneId) + "/activity"
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneClose entspricht MCP-Tool devd_milestone_close.
func (c *Client) MilestoneClose(args generated.MilestoneCloseArgs) (json.RawMessage, error) {
	body := map[string]any{}
	if args.TargetStatus != nil {
		body["target_status"] = *args.TargetStatus
	}
	if args.Assignments != nil {
		body["assignments"] = args.Assignments
	}
	path := "/api/milestones/" + fmt.Sprintf("%v", args.MilestoneId) + "/close-with-issues"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneCreate entspricht MCP-Tool devd_milestone_create.
func (c *Client) MilestoneCreate(args generated.MilestoneCreateArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["name"] = args.Name
	if args.Description != nil {
		body["description"] = *args.Description
	}
	if args.TargetDate != nil {
		body["target_date"] = *args.TargetDate
	}
	if args.Status != nil {
		body["status"] = *args.Status
	}
	path := "/api/milestones"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneDelete entspricht MCP-Tool devd_milestone_delete.
func (c *Client) MilestoneDelete(args generated.MilestoneDeleteArgs) (json.RawMessage, error) {
	q := url.Values{}
	if args.Cascade {
		q.Set("cascade", "1")
	}
	path := "/api/milestones/" + fmt.Sprintf("%v", args.MilestoneId)
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("DELETE", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneDepAdd entspricht MCP-Tool devd_milestone_dep_add.
func (c *Client) MilestoneDepAdd(args generated.MilestoneDepAddArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["predecessor_id"] = args.PredecessorId
	body["successor_id"] = args.SuccessorId
	path := "/api/milestone-dependencies"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneDepList entspricht MCP-Tool devd_milestone_dep_list.
func (c *Client) MilestoneDepList(args generated.MilestoneDepListArgs) (json.RawMessage, error) {
	path := "/api/milestones/" + fmt.Sprintf("%v", args.MilestoneId) + "/dependencies"
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneDepRemove entspricht MCP-Tool devd_milestone_dep_remove.
func (c *Client) MilestoneDepRemove(args generated.MilestoneDepRemoveArgs) (json.RawMessage, error) {
	path := "/api/milestone-dependencies/" + fmt.Sprintf("%v", args.DependencyId)
	data, err := c.Do("DELETE", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneDodAdd entspricht MCP-Tool devd_milestone_dod_add.
func (c *Client) MilestoneDodAdd(args generated.MilestoneDodAddArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["label"] = args.Label
	path := "/api/milestones/" + fmt.Sprintf("%v", args.MilestoneId) + "/dod-items"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneDodDelete entspricht MCP-Tool devd_milestone_dod_delete.
func (c *Client) MilestoneDodDelete(args generated.MilestoneDodDeleteArgs) (json.RawMessage, error) {
	path := "/api/dod-items/" + fmt.Sprintf("%v", args.ItemId)
	data, err := c.Do("DELETE", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneDodList entspricht MCP-Tool devd_milestone_dod_list.
func (c *Client) MilestoneDodList(args generated.MilestoneDodListArgs) (json.RawMessage, error) {
	path := "/api/milestones/" + fmt.Sprintf("%v", args.MilestoneId) + "/dod-items"
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneDodReorder entspricht MCP-Tool devd_milestone_dod_reorder.
func (c *Client) MilestoneDodReorder(args generated.MilestoneDodReorderArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["order"] = args.Order
	path := "/api/milestones/" + fmt.Sprintf("%v", args.MilestoneId) + "/dod-items/reorder"
	data, err := c.Do("PATCH", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneDodSet entspricht MCP-Tool devd_milestone_dod_set.
func (c *Client) MilestoneDodSet(args generated.MilestoneDodSetArgs) (json.RawMessage, error) {
	body := map[string]any{}
	if args.Label != nil {
		body["label"] = *args.Label
	}
	if args.Done != nil && *args.Done {
		body["done"] = *args.Done
	}
	path := "/api/dod-items/" + fmt.Sprintf("%v", args.ItemId)
	data, err := c.Do("PATCH", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneList entspricht MCP-Tool devd_milestone_list.
func (c *Client) MilestoneList(args generated.MilestoneListArgs) (json.RawMessage, error) {
	q := url.Values{}
	if args.Status != nil {
		q.Set("status", *args.Status)
	}
	path := "/api/milestones"
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneReorder entspricht MCP-Tool devd_milestone_reorder.
func (c *Client) MilestoneReorder(args generated.MilestoneReorderArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["ordered_ids"] = args.OrderedIds
	path := "/api/milestones/reorder"
	data, err := c.Do("PATCH", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneShow entspricht MCP-Tool devd_milestone_show.
func (c *Client) MilestoneShow(args generated.MilestoneShowArgs) (json.RawMessage, error) {
	path := "/api/milestones/" + fmt.Sprintf("%v", args.MilestoneId)
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneStatus entspricht MCP-Tool devd_milestone_status.
func (c *Client) MilestoneStatus(args generated.MilestoneStatusArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["status"] = args.Status
	if args.Notes != nil {
		body["cancellation_notes"] = *args.Notes
	}
	path := "/api/milestones/" + fmt.Sprintf("%v", args.MilestoneId)
	data, err := c.Do("PUT", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// MilestoneUpdate entspricht MCP-Tool devd_milestone_update.
func (c *Client) MilestoneUpdate(args generated.MilestoneUpdateArgs) (json.RawMessage, error) {
	body := map[string]any{}
	if args.Name != nil {
		body["name"] = *args.Name
	}
	if args.Description != nil {
		body["description"] = *args.Description
	}
	if args.TargetDate != nil {
		body["target_date"] = *args.TargetDate
	}
	path := "/api/milestones/" + fmt.Sprintf("%v", args.MilestoneId)
	data, err := c.Do("PUT", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// ProjectList entspricht MCP-Tool devd_project_list.
func (c *Client) ProjectList(args generated.ProjectListArgs) (json.RawMessage, error) {
	q := url.Values{}
	if args.IncludeArchived != nil && *args.IncludeArchived {
		q.Set("include_archived", "1")
	}
	if args.Fields != nil {
		q.Set("fields", string(*args.Fields))
	}
	path := "/api/projects"
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// ProjectMemoryAnchorGet entspricht MCP-Tool devd_project_memory_anchor_get.
func (c *Client) ProjectMemoryAnchorGet(args generated.ProjectMemoryAnchorGetArgs) (json.RawMessage, error) {
	path := "/api/project-memories/anchor/" + url.PathEscape(args.Anchor)
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// ProjectMemoryDelete entspricht MCP-Tool devd_project_memory_delete.
func (c *Client) ProjectMemoryDelete(args generated.ProjectMemoryDeleteArgs) (json.RawMessage, error) {
	path := "/api/project-memories/" + fmt.Sprintf("%v", args.Id)
	data, err := c.Do("DELETE", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// ProjectMemoryList entspricht MCP-Tool devd_project_memory_list.
func (c *Client) ProjectMemoryList(args generated.ProjectMemoryListArgs) (json.RawMessage, error) {
	q := url.Values{}
	if args.Category != nil {
		q.Set("category", string(*args.Category))
	}
	if args.Fields != nil {
		q.Set("fields", string(*args.Fields))
	}
	if args.Limit != nil {
		q.Set("limit", fmt.Sprintf("%v", *args.Limit))
	}
	if args.Offset != nil {
		q.Set("offset", fmt.Sprintf("%v", *args.Offset))
	}
	path := "/api/project-memories"
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// ProjectMemoryLog entspricht MCP-Tool devd_project_memory_log.
func (c *Client) ProjectMemoryLog(args generated.ProjectMemoryLogArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["category"] = args.Category
	body["summary"] = args.Summary
	if args.Content != nil {
		body["content"] = *args.Content
	}
	body["tags"] = args.Tags
	if args.Importance != nil {
		body["importance"] = *args.Importance
	}
	if args.Pinned != nil && *args.Pinned {
		body["pinned"] = *args.Pinned
	}
	if args.Anchor != nil {
		body["anchor"] = *args.Anchor
	}
	if args.Stability != nil {
		body["stability"] = *args.Stability
	}
	if args.SourceType != nil {
		body["source_type"] = *args.SourceType
	}
	if args.SourceRef != nil {
		body["source_ref"] = *args.SourceRef
	}
	path := "/api/project-memories"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// ProjectMemoryQuery entspricht MCP-Tool devd_project_memory_query.
func (c *Client) ProjectMemoryQuery(args generated.ProjectMemoryQueryArgs) (json.RawMessage, error) {
	q := url.Values{}
	q.Set("q", args.Q)
	if args.Category != nil {
		q.Set("category", string(*args.Category))
	}
	if args.Limit != nil {
		q.Set("limit", fmt.Sprintf("%v", *args.Limit))
	}
	path := "/api/project-memories/search"
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// ProjectMemoryShow entspricht MCP-Tool devd_project_memory_show.
func (c *Client) ProjectMemoryShow(args generated.ProjectMemoryShowArgs) (json.RawMessage, error) {
	path := "/api/project-memories/" + fmt.Sprintf("%v", args.Id)
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// ProjectMemorySupersede entspricht MCP-Tool devd_project_memory_supersede.
func (c *Client) ProjectMemorySupersede(args generated.ProjectMemorySupersedeArgs) (json.RawMessage, error) {
	body := map[string]any{}
	if args.Category != nil {
		body["category"] = *args.Category
	}
	if args.Summary != nil {
		body["summary"] = *args.Summary
	}
	if args.Content != nil {
		body["content"] = *args.Content
	}
	body["tags"] = args.Tags
	if args.Importance != nil {
		body["importance"] = *args.Importance
	}
	if args.Pinned != nil && *args.Pinned {
		body["pinned"] = *args.Pinned
	}
	if args.Anchor != nil {
		body["anchor"] = *args.Anchor
	}
	if args.Stability != nil {
		body["stability"] = *args.Stability
	}
	if args.SourceType != nil {
		body["source_type"] = *args.SourceType
	}
	if args.SourceRef != nil {
		body["source_ref"] = *args.SourceRef
	}
	path := "/api/project-memories/" + fmt.Sprintf("%v", args.Id) + "/supersede"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// ProjectMemoryUpdate entspricht MCP-Tool devd_project_memory_update.
func (c *Client) ProjectMemoryUpdate(args generated.ProjectMemoryUpdateArgs) (json.RawMessage, error) {
	body := map[string]any{}
	if args.Category != nil {
		body["category"] = *args.Category
	}
	if args.Summary != nil {
		body["summary"] = *args.Summary
	}
	if args.Content != nil {
		body["content"] = *args.Content
	}
	body["tags"] = args.Tags
	if args.Importance != nil {
		body["importance"] = *args.Importance
	}
	if args.Pinned != nil && *args.Pinned {
		body["pinned"] = *args.Pinned
	}
	if args.Anchor != nil {
		body["anchor"] = *args.Anchor
	}
	if args.Stability != nil {
		body["stability"] = *args.Stability
	}
	if args.SourceType != nil {
		body["source_type"] = *args.SourceType
	}
	if args.SourceRef != nil {
		body["source_ref"] = *args.SourceRef
	}
	path := "/api/project-memories/" + fmt.Sprintf("%v", args.Id)
	data, err := c.Do("PATCH", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// ProjectShow entspricht MCP-Tool devd_project_show.
func (c *Client) ProjectShow(args generated.ProjectShowArgs) (json.RawMessage, error) {
	path := "/api/projects/" + url.PathEscape(fmt.Sprintf("%v", args.IdOrSlug))
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// ReviewCreate entspricht MCP-Tool devd_review_create.
func (c *Client) ReviewCreate(args generated.ReviewCreateArgs) (json.RawMessage, error) {
	var err error
	idOrKeyIssueID, err := c.ResolveIssueID(args.IdOrKey)
	if err != nil {
		return nil, err
	}
	body := map[string]any{}
	body["review_status"] = args.Verdict
	if args.Comment != nil {
		body["comment"] = *args.Comment
	}
	if args.Notes != nil {
		body["notes"] = *args.Notes
	}
	path := "/api/backlog/" + fmt.Sprintf("%d", idOrKeyIssueID) + "/reviews"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// ReviewReopen entspricht MCP-Tool devd_review_reopen.
func (c *Client) ReviewReopen(args generated.ReviewReopenArgs) (json.RawMessage, error) {
	var err error
	idOrKeyIssueID, err := c.ResolveIssueID(args.IdOrKey)
	if err != nil {
		return nil, err
	}
	body := map[string]any{}
	path := "/api/backlog/" + fmt.Sprintf("%d", idOrKeyIssueID) + "/review/reopen"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintActivity entspricht MCP-Tool devd_sprint_activity.
func (c *Client) SprintActivity(args generated.SprintActivityArgs) (json.RawMessage, error) {
	var err error
	sprintKeySprintID, err := c.ResolveSprintID(args.SprintKey)
	if err != nil {
		return nil, err
	}
	q := url.Values{}
	if args.Limit != nil {
		q.Set("limit", fmt.Sprintf("%v", *args.Limit))
	}
	path := "/api/sprints/" + fmt.Sprintf("%d", sprintKeySprintID) + "/activity"
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintCancel entspricht MCP-Tool devd_sprint_cancel.
func (c *Client) SprintCancel(args generated.SprintCancelArgs) (json.RawMessage, error) {
	var err error
	sprintKeySprintID, err := c.ResolveSprintID(args.SprintKey)
	if err != nil {
		return nil, err
	}
	body := map[string]any{}
	body["to"] = "cancelled"
	body["cancellationNotes"] = args.Notes
	path := "/api/sprints/" + fmt.Sprintf("%d", sprintKeySprintID) + "/status"
	data, err := c.Do("PATCH", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintContext entspricht MCP-Tool devd_sprint_context.
func (c *Client) SprintContext(args generated.SprintContextArgs) (json.RawMessage, error) {
	var err error
	sprintKeySprintID, err := c.ResolveSprintID(args.SprintKey)
	if err != nil {
		return nil, err
	}
	path := "/api/sprints/" + fmt.Sprintf("%d", sprintKeySprintID) + "/context?format=markdown"
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintCreate entspricht MCP-Tool devd_sprint_create.
func (c *Client) SprintCreate(args generated.SprintCreateArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["name"] = args.Name
	if args.Goal != nil {
		body["goal"] = *args.Goal
	}
	if args.Notes != nil {
		body["notes"] = *args.Notes
	}
	if args.StartDate != nil {
		body["start_date"] = *args.StartDate
	}
	if args.EndDate != nil {
		body["end_date"] = *args.EndDate
	}
	if args.Capacity != nil {
		body["capacity"] = *args.Capacity
	}
	if args.WipLimit != nil {
		body["wip_limit"] = *args.WipLimit
	}
	if args.MilestoneId != nil {
		body["milestone_id"] = *args.MilestoneId
	}
	path := "/api/sprints"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintDelete entspricht MCP-Tool devd_sprint_delete.
func (c *Client) SprintDelete(args generated.SprintDeleteArgs) (json.RawMessage, error) {
	var err error
	sprintKeySprintID, err := c.ResolveSprintID(args.SprintKey)
	if err != nil {
		return nil, err
	}
	q := url.Values{}
	if args.Cascade {
		q.Set("cascade", "1")
	}
	path := "/api/sprints/" + fmt.Sprintf("%d", sprintKeySprintID)
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("DELETE", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintDepAdd entspricht MCP-Tool devd_sprint_dep_add.
func (c *Client) SprintDepAdd(args generated.SprintDepAddArgs) (json.RawMessage, error) {
	var err error
	predecessorIdSprintID, err := c.ResolveSprintID(fmt.Sprintf("%v", args.PredecessorId))
	if err != nil {
		return nil, err
	}
	successorIdSprintID, err := c.ResolveSprintID(fmt.Sprintf("%v", args.SuccessorId))
	if err != nil {
		return nil, err
	}
	body := map[string]any{}
	body["predecessor_id"] = predecessorIdSprintID
	body["successor_id"] = successorIdSprintID
	path := "/api/sprint-dependencies"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintDepList entspricht MCP-Tool devd_sprint_dep_list.
func (c *Client) SprintDepList(args generated.SprintDepListArgs) (json.RawMessage, error) {
	var err error
	sprintKeySprintID, err := c.ResolveSprintID(args.SprintKey)
	if err != nil {
		return nil, err
	}
	path := "/api/sprints/" + fmt.Sprintf("%d", sprintKeySprintID) + "/dependencies"
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintDepRemove entspricht MCP-Tool devd_sprint_dep_remove.
func (c *Client) SprintDepRemove(args generated.SprintDepRemoveArgs) (json.RawMessage, error) {
	path := "/api/sprint-dependencies/" + fmt.Sprintf("%v", args.DependencyId)
	data, err := c.Do("DELETE", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintExport entspricht MCP-Tool devd_sprint_export.
func (c *Client) SprintExport(args generated.SprintExportArgs) (json.RawMessage, error) {
	var err error
	sprintKeySprintID, err := c.ResolveSprintID(args.SprintKey)
	if err != nil {
		return nil, err
	}
	q := url.Values{}
	if args.Format != nil {
		q.Set("format", string(*args.Format))
	}
	path := "/api/sprints/" + fmt.Sprintf("%d", sprintKeySprintID) + "/export"
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintList entspricht MCP-Tool devd_sprint_list.
func (c *Client) SprintList(args generated.SprintListArgs) (json.RawMessage, error) {
	q := url.Values{}
	if args.Status != nil {
		q.Set("status", *args.Status)
	}
	if args.MilestoneId != nil {
		q.Set("milestone_id", fmt.Sprintf("%v", args.MilestoneId))
	}
	if args.Fields != nil {
		q.Set("fields", string(*args.Fields))
	}
	if args.Limit != nil {
		q.Set("limit", fmt.Sprintf("%v", *args.Limit))
	}
	if args.Offset != nil {
		q.Set("offset", fmt.Sprintf("%v", *args.Offset))
	}
	path := "/api/sprints"
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintReorder entspricht MCP-Tool devd_sprint_reorder.
func (c *Client) SprintReorder(args generated.SprintReorderArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["ordered_ids"] = args.OrderedIds
	path := "/api/sprints/reorder"
	data, err := c.Do("PATCH", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintReview entspricht MCP-Tool devd_sprint_review.
func (c *Client) SprintReview(args generated.SprintReviewArgs) (json.RawMessage, error) {
	var err error
	sprintKeySprintID, err := c.ResolveSprintID(args.SprintKey)
	if err != nil {
		return nil, err
	}
	body := map[string]any{}
	body["to"] = "to_review"
	path := "/api/sprints/" + fmt.Sprintf("%d", sprintKeySprintID) + "/status"
	data, err := c.Do("PATCH", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintSetMilestone entspricht MCP-Tool devd_sprint_set_milestone.
func (c *Client) SprintSetMilestone(args generated.SprintSetMilestoneArgs) (json.RawMessage, error) {
	var err error
	idOrKeySprintID, err := c.ResolveSprintID(args.IdOrKey)
	if err != nil {
		return nil, err
	}
	body := map[string]any{}
	if args.MilestoneId != nil {
		body["milestone_id"] = *args.MilestoneId
	}
	path := "/api/sprints/" + fmt.Sprintf("%d", idOrKeySprintID)
	data, err := c.Do("PUT", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintShow entspricht MCP-Tool devd_sprint_show.
func (c *Client) SprintShow(args generated.SprintShowArgs) (json.RawMessage, error) {
	var err error
	sprintKeySprintID, err := c.ResolveSprintID(args.SprintKey)
	if err != nil {
		return nil, err
	}
	path := "/api/sprints/" + fmt.Sprintf("%d", sprintKeySprintID)
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintStart entspricht MCP-Tool devd_sprint_start.
func (c *Client) SprintStart(args generated.SprintStartArgs) (json.RawMessage, error) {
	var err error
	sprintKeySprintID, err := c.ResolveSprintID(args.SprintKey)
	if err != nil {
		return nil, err
	}
	body := map[string]any{}
	body["to"] = "in_progress"
	path := "/api/sprints/" + fmt.Sprintf("%d", sprintKeySprintID) + "/status"
	data, err := c.Do("PATCH", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SprintUpdate entspricht MCP-Tool devd_sprint_update.
func (c *Client) SprintUpdate(args generated.SprintUpdateArgs) (json.RawMessage, error) {
	var err error
	idOrKeySprintID, err := c.ResolveSprintID(args.IdOrKey)
	if err != nil {
		return nil, err
	}
	body := map[string]any{}
	if args.Name != nil {
		body["name"] = *args.Name
	}
	if args.Goal != nil {
		body["goal"] = *args.Goal
	}
	if args.Notes != nil {
		body["notes"] = *args.Notes
	}
	if args.StartDate != nil {
		body["start_date"] = *args.StartDate
	}
	if args.EndDate != nil {
		body["end_date"] = *args.EndDate
	}
	if args.Capacity != nil {
		body["capacity"] = *args.Capacity
	}
	if args.WipLimit != nil {
		body["wip_limit"] = *args.WipLimit
	}
	path := "/api/sprints/" + fmt.Sprintf("%d", idOrKeySprintID)
	data, err := c.Do("PUT", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SubtaskAdd entspricht MCP-Tool devd_subtask_add.
func (c *Client) SubtaskAdd(args generated.SubtaskAddArgs) (json.RawMessage, error) {
	var err error
	idOrKeyIssueID, err := c.ResolveIssueID(args.IdOrKey)
	if err != nil {
		return nil, err
	}
	body := map[string]any{}
	body["title"] = args.Title
	if args.QaCriteria != nil {
		body["qa_criteria"] = *args.QaCriteria
	}
	if args.Position != nil {
		body["position"] = *args.Position
	}
	path := "/api/backlog/" + fmt.Sprintf("%d", idOrKeyIssueID) + "/subtasks"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SubtaskDone entspricht MCP-Tool devd_subtask_done.
func (c *Client) SubtaskDone(args generated.SubtaskDoneArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["status"] = "done"
	path := "/api/subtasks/" + fmt.Sprintf("%v", args.SubtaskId) + "/status"
	data, err := c.Do("PATCH", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SubtaskEdit entspricht MCP-Tool devd_subtask_edit.
func (c *Client) SubtaskEdit(args generated.SubtaskEditArgs) (json.RawMessage, error) {
	body := map[string]any{}
	if args.Title != nil {
		body["title"] = *args.Title
	}
	if args.QaCriteria != nil {
		body["qa_criteria"] = *args.QaCriteria
	}
	if args.Position != nil {
		body["position"] = *args.Position
	}
	path := "/api/subtasks/" + fmt.Sprintf("%v", args.SubtaskId)
	data, err := c.Do("PATCH", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SubtaskList entspricht MCP-Tool devd_subtask_list.
func (c *Client) SubtaskList(args generated.SubtaskListArgs) (json.RawMessage, error) {
	var err error
	idOrKeyIssueID, err := c.ResolveIssueID(args.IdOrKey)
	if err != nil {
		return nil, err
	}
	path := "/api/backlog/" + fmt.Sprintf("%d", idOrKeyIssueID) + "/subtasks"
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// SubtaskRemove entspricht MCP-Tool devd_subtask_remove.
func (c *Client) SubtaskRemove(args generated.SubtaskRemoveArgs) (json.RawMessage, error) {
	path := "/api/subtasks/" + fmt.Sprintf("%v", args.SubtaskId)
	data, err := c.Do("DELETE", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// TagCreate entspricht MCP-Tool devd_tag_create.
func (c *Client) TagCreate(args generated.TagCreateArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["name"] = args.Name
	if args.Color != nil {
		body["color"] = *args.Color
	}
	path := "/api/tags"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// TagDelete entspricht MCP-Tool devd_tag_delete.
func (c *Client) TagDelete(args generated.TagDeleteArgs) (json.RawMessage, error) {
	path := "/api/tags/" + fmt.Sprintf("%v", args.Id)
	data, err := c.Do("DELETE", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// TagList entspricht MCP-Tool devd_tag_list.
func (c *Client) TagList(args generated.TagListArgs) (json.RawMessage, error) {
	path := "/api/tags"
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// TagUpdate entspricht MCP-Tool devd_tag_update.
func (c *Client) TagUpdate(args generated.TagUpdateArgs) (json.RawMessage, error) {
	body := map[string]any{}
	if args.Name != nil {
		body["name"] = *args.Name
	}
	if args.Color != nil {
		body["color"] = *args.Color
	}
	path := "/api/tags/" + fmt.Sprintf("%v", args.Id)
	data, err := c.Do("PUT", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// TodoCreate entspricht MCP-Tool devd_todo_create.
func (c *Client) TodoCreate(args generated.TodoCreateArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["label"] = args.Label
	if args.Details != nil {
		body["details"] = *args.Details
	}
	path := "/api/projects/" + url.PathEscape(c.ProjectID()) + "/todos"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// TodoDelete entspricht MCP-Tool devd_todo_delete.
func (c *Client) TodoDelete(args generated.TodoDeleteArgs) (json.RawMessage, error) {
	path := "/api/projects/" + url.PathEscape(c.ProjectID()) + "/todos/" + fmt.Sprintf("%v", args.Id)
	data, err := c.Do("DELETE", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// TodoLink entspricht MCP-Tool devd_todo_link.
func (c *Client) TodoLink(args generated.TodoLinkArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["type"] = args.Type
	body["target"] = args.Target
	path := "/api/projects/" + url.PathEscape(c.ProjectID()) + "/todos/" + fmt.Sprintf("%v", args.Id) + "/links"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// TodoList entspricht MCP-Tool devd_todo_list.
func (c *Client) TodoList(args generated.TodoListArgs) (json.RawMessage, error) {
	q := url.Values{}
	if args.Status != nil {
		q.Set("status", string(*args.Status))
	}
	path := "/api/projects/" + url.PathEscape(c.ProjectID()) + "/todos"
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// TodoShow entspricht MCP-Tool devd_todo_show.
func (c *Client) TodoShow(args generated.TodoShowArgs) (json.RawMessage, error) {
	path := "/api/projects/" + url.PathEscape(c.ProjectID()) + "/todos"
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// TodoUpdate entspricht MCP-Tool devd_todo_update.
func (c *Client) TodoUpdate(args generated.TodoUpdateArgs) (json.RawMessage, error) {
	body := map[string]any{}
	if args.Label != nil {
		body["label"] = *args.Label
	}
	if args.Status != nil {
		body["status"] = *args.Status
	}
	if args.Details != nil {
		body["details"] = *args.Details
	}
	path := "/api/projects/" + url.PathEscape(c.ProjectID()) + "/todos/" + fmt.Sprintf("%v", args.Id)
	data, err := c.Do("PATCH", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// UserNoteCreate entspricht MCP-Tool devd_user_note_create.
func (c *Client) UserNoteCreate(args generated.UserNoteCreateArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["title"] = args.Title
	if args.Details != nil {
		body["details"] = *args.Details
	}
	if args.PrUrl != nil {
		body["pr_url"] = *args.PrUrl
	}
	body["sprints"] = args.Sprints
	body["issues"] = args.Issues
	path := "/api/user-notes"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// UserNoteDelete entspricht MCP-Tool devd_user_note_delete.
func (c *Client) UserNoteDelete(args generated.UserNoteDeleteArgs) (json.RawMessage, error) {
	path := "/api/user-notes/" + fmt.Sprintf("%v", args.Id)
	data, err := c.Do("DELETE", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// UserNoteGet entspricht MCP-Tool devd_user_note_get.
func (c *Client) UserNoteGet(args generated.UserNoteGetArgs) (json.RawMessage, error) {
	path := "/api/user-notes/" + fmt.Sprintf("%v", args.Id)
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// UserNoteList entspricht MCP-Tool devd_user_note_list.
func (c *Client) UserNoteList(args generated.UserNoteListArgs) (json.RawMessage, error) {
	q := url.Values{}
	if args.Search != nil {
		q.Set("search", *args.Search)
	}
	path := "/api/user-notes"
	if len(q) > 0 {
		path += "?" + q.Encode()
	}
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// UserNoteUpdate entspricht MCP-Tool devd_user_note_update.
func (c *Client) UserNoteUpdate(args generated.UserNoteUpdateArgs) (json.RawMessage, error) {
	body := map[string]any{}
	if args.Title != nil {
		body["title"] = *args.Title
	}
	if args.Details != nil {
		body["details"] = *args.Details
	}
	if args.PrUrl != nil {
		body["pr_url"] = *args.PrUrl
	}
	body["sprints"] = args.Sprints
	body["issues"] = args.Issues
	path := "/api/user-notes/" + fmt.Sprintf("%v", args.Id)
	data, err := c.Do("PUT", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// UserStoryAdd entspricht MCP-Tool devd_user_story_add.
func (c *Client) UserStoryAdd(args generated.UserStoryAddArgs) (json.RawMessage, error) {
	var err error
	issueIdOrKeyIssueID, err := c.ResolveIssueID(args.IssueIdOrKey)
	if err != nil {
		return nil, err
	}
	body := map[string]any{}
	body["title"] = args.Title
	if args.Details != nil {
		body["details"] = *args.Details
	}
	if args.Qa != nil {
		body["qa"] = *args.Qa
	}
	if args.Position != nil {
		body["position"] = *args.Position
	}
	path := "/api/backlog/" + fmt.Sprintf("%d", issueIdOrKeyIssueID) + "/user-stories"
	data, err := c.Do("POST", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// UserStoryEdit entspricht MCP-Tool devd_user_story_edit.
func (c *Client) UserStoryEdit(args generated.UserStoryEditArgs) (json.RawMessage, error) {
	body := map[string]any{}
	if args.Title != nil {
		body["title"] = *args.Title
	}
	if args.Details != nil {
		body["details"] = *args.Details
	}
	if args.Qa != nil {
		body["qa"] = *args.Qa
	}
	if args.UsVerdict != nil {
		body["us_verdict"] = *args.UsVerdict
	}
	if args.Position != nil {
		body["position"] = *args.Position
	}
	path := "/api/user-stories/" + fmt.Sprintf("%v", args.UserStoryId)
	data, err := c.Do("PATCH", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// UserStoryList entspricht MCP-Tool devd_user_story_list.
func (c *Client) UserStoryList(args generated.UserStoryListArgs) (json.RawMessage, error) {
	var err error
	idOrKeyIssueID, err := c.ResolveIssueID(args.IdOrKey)
	if err != nil {
		return nil, err
	}
	path := "/api/backlog/" + fmt.Sprintf("%d", idOrKeyIssueID) + "/user-stories"
	data, err := c.Do("GET", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// UserStoryRemove entspricht MCP-Tool devd_user_story_remove.
func (c *Client) UserStoryRemove(args generated.UserStoryRemoveArgs) (json.RawMessage, error) {
	path := "/api/user-stories/" + fmt.Sprintf("%v", args.UserStoryId)
	data, err := c.Do("DELETE", path, nil)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

// UserStoryVerdict entspricht MCP-Tool devd_user_story_verdict.
func (c *Client) UserStoryVerdict(args generated.UserStoryVerdictArgs) (json.RawMessage, error) {
	body := map[string]any{}
	body["us_verdict"] = args.UsVerdict
	path := "/api/user-stories/" + fmt.Sprintf("%v", args.UserStoryId) + "/verdict"
	data, err := c.Do("PATCH", path, body)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}
