#!/usr/bin/env node
/**
 * gen-types.mjs — Arg-Struct-Emitter (DD2-202)
 *
 * Emittiert apps/cli-go/internal/api/generated/generated_types.go (`package generated`):
 * ein Arg-Struct je MCP-Tool, plus Sub-Structs für nested objects und benannte
 * const-Blöcke für enums — alles über die zentrale Typmapping-Schicht (DD2-201).
 *
 * Package-Isolation (D01 DD2#34): `generated` statt `api`, damit parallele Sprints
 * (z.B. DD2#32, die in package api neue Typen anlegen) kollisionsfrei mergen.
 *
 *   node apps/cli-go/codegen/gen-types.mjs
 *
 * Out-of-Scope: apiRequest/Transport + Client-Funcs (DD2#35), Freshness-Gate (DD2#37).
 */
import { execFileSync } from 'child_process'
import { writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import { introspect } from './introspect.mjs'
import { shapeToJsonSchema } from './capabilities.mjs'
import { mapSchema, needsPointer, jsonTag, pascalCase } from './typemap.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT_FILE = join(__dirname, '..', 'internal', 'api', 'generated', 'generated_types.go')

/** enum-Wert → exportierter Go-Identifier-Suffix (nicht-alphanumerisch → entfernt). */
function enumIdent(value) {
  const id = pascalCase(String(value).replace(/[^A-Za-z0-9]+/g, '_'))
  return id || '_'
}

/** Doc-Kommentar aus description (einzeilig, Go-`//`). Leer → ''. */
function docComment(desc, indent = '') {
  const flat = (desc || '').replace(/\s+/g, ' ').trim()
  return flat ? `${indent}// ${flat}\n` : ''
}

/**
 * renderType(descriptor, nameHint) → { type, decls }
 *   type  = Go-Typ-String fürs Feld (inkl. Pointer/Slice)
 *   decls = abhängige Top-Level-Deklarationen (Sub-Structs, enum-const-Blöcke)
 */
function renderType(d, nameHint) {
  const decls = []
  let t
  switch (d.kind) {
    case 'scalar':
      t = d.goType
      break
    case 'any':
      t = 'any'
      break
    case 'enum':
      decls.push(renderEnum(nameHint, d))
      t = nameHint
      break
    case 'array': {
      const r = renderType(d.elem, `${nameHint}Item`)
      decls.push(...r.decls)
      t = `[]${r.type}` // Slices nie Pointer (nil = leer)
      return { type: t, decls }
    }
    case 'object': {
      const r = renderStruct(nameHint, d)
      decls.push(...r.decls, r.text) // Sub-Deklarationen + die Struct selbst
      t = nameHint
      break
    }
    default:
      t = 'any'
  }
  if (needsPointer(d)) t = `*${t}`
  return { type: t, decls }
}

/** renderEnum(typeName, descriptor) → benannter String-Typ + const-Block. */
function renderEnum(typeName, d) {
  const lines = [`type ${typeName} ${d.base}`, '', 'const (']
  for (const v of d.enumValues) {
    lines.push(`\t${typeName}${enumIdent(v)} ${typeName} = ${JSON.stringify(v)}`)
  }
  lines.push(')')
  return lines.join('\n')
}

/** renderStruct(structName, objectDescriptor) → { text, decls } (decls = Sub-Deklarationen). */
function renderStruct(structName, d) {
  const decls = []
  const lines = [`type ${structName} struct {`]
  for (const key of Object.keys(d.fields)) {
    const fd = d.fields[key]
    const fieldName = pascalCase(key)
    const r = renderType(fd, `${structName}${fieldName}`)
    decls.push(...r.decls)
    const tag = jsonTag(key, fd)
    const doc = docComment(fd.description, '\t')
    lines.push(`${doc}\t${fieldName} ${r.type} \`json:"${tag}"\``)
  }
  lines.push('}')
  return { text: lines.join('\n'), decls }
}

function generate(tools) {
  const sorted = [...tools].sort((a, b) => a.name.localeCompare(b.name))
  const blocks = []
  let structCount = 0
  for (const t of sorted) {
    const schema = shapeToJsonSchema(t.zodShape)
    const objDesc = mapSchema(schema, true) // Top-Level inputSchema = object
    const structName = `${pascalCase(t.name.replace(/^devd_/, ''))}Args`
    const { text, decls } = renderStruct(structName, objDesc)
    structCount++
    const head = docComment(`${structName}: Argumente für MCP-Tool ${t.name}.`)
    // Sub-Deklarationen vor dem Haupt-Struct, damit go vet/Leser sie zuerst sehen.
    blocks.push([...decls, head + text].join('\n\n'))
  }
  const header =
    '// Code generated by apps/cli-go/codegen/gen-types.mjs; DO NOT EDIT.\n' +
    '//\n' +
    '// Quelle: apps/cli/mcp/devd-mcp.js (via Introspektions-Harness DD2-199).\n' +
    '// Ein Arg-Struct je MCP-Tool über die Zod→Go-Typmapping-Schicht (DD2-201).\n' +
    '// Regenerieren: node apps/cli-go/codegen/gen-types.mjs\n\n' +
    'package generated\n'
  return { src: header + '\n' + blocks.join('\n\n') + '\n', structCount }
}

export async function emitTypes() {
  const tools = await introspect()
  const { src, structCount } = generate(tools)
  writeFileSync(OUT_FILE, src)
  // gofmt direkt anwenden — kanonische Formatierung, stabil fürs Diff-Gate (DD2#37).
  execFileSync('gofmt', ['-w', OUT_FILE])
  return { outFile: OUT_FILE, structCount }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { outFile, structCount } = await emitTypes()
  console.log(`OK: ${structCount} Arg-Structs → ${outFile}`)
}
